# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rivian_charging.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rivian_charging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import rivian_base_pb2 as rivian__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15rivian_charging.proto\x12\x06rivian\x1a\x11rivian_base.proto\"\xde\x02\n\x17\x43hargingSessionLiveData\x12\x11\n\ttotal_kwh\x18\x01 \x01(\x02\x12\x10\n\x08pack_kwh\x18\x02 \x01(\x02\x12\x13\n\x0bthermal_kwh\x18\x03 \x01(\x02\x12\x13\n\x0boutlets_kwh\x18\x04 \x01(\x02\x12\x12\n\nsystem_kwh\x18\x05 \x01(\x02\x12\x1d\n\x15session_duration_mins\x18\x06 \x01(\x05\x12\x1b\n\x13time_remaining_mins\x18\x07 \x01(\x05\x12\x17\n\x0frange_added_kms\x18\x08 \x01(\x05\x12\x15\n\rcurrent_power\x18\t \x01(\x02\x12\x1e\n\x16\x63urrent_range_per_hour\x18\n \x01(\x05\x12#\n\x0csession_cost\x18\x0b \x01(\x0b\x32\r.rivian.Money\x12\x17\n\x0fis_free_session\x18\x0c \x01(\x08\x12\x16\n\x0e\x63harging_state\x18\r \x01(\x05\"\xaa\x01\n\nWindowData\x12\x12\n\nstart_time\x18\x01 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x05\x12\x10\n\x08\x64uration\x18\x03 \x01(\x05\x12\x0c\n\x04\x61mps\x18\x04 \x01(\x05\x12\"\n\x08location\x18\x05 \x01(\x0b\x32\x10.rivian.Location\x12\x19\n\x11start_day_of_week\x18\x06 \x01(\x05\x12\x17\n\x0f\x65nd_day_of_week\x18\x07 \x01(\x05\"W\n\x1a\x43hargingScheduleTimeWindow\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\'\n\x0bwindow_data\x18\x02 \x01(\x0b\x32\x12.rivian.WindowData\"\xd0\x01\n\x18\x43hargingSessionChartData\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\ntimestamps\x18\x02 \x03(\x03\x12\x14\n\x0cpower_values\x18\x03 \x03(\x02\x12\x12\n\nsoc_values\x18\x04 \x03(\x02\x12\x16\n\x0evoltage_values\x18\x05 \x03(\x02\x12\x16\n\x0e\x63urrent_values\x18\x06 \x03(\x02\x12\x18\n\x10total_energy_kwh\x18\x07 \x01(\x02\x12\x18\n\x10\x64uration_minutes\x18\x08 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rivian_charging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHARGINGSESSIONLIVEDATA']._serialized_start=53
  _globals['_CHARGINGSESSIONLIVEDATA']._serialized_end=403
  _globals['_WINDOWDATA']._serialized_start=406
  _globals['_WINDOWDATA']._serialized_end=576
  _globals['_CHARGINGSCHEDULETIMEWINDOW']._serialized_start=578
  _globals['_CHARGINGSCHEDULETIMEWINDOW']._serialized_end=665
  _globals['_CHARGINGSESSIONCHARTDATA']._serialized_start=668
  _globals['_CHARGINGSESSIONCHARTDATA']._serialized_end=876
# @@protoc_insertion_point(module_scope)
