# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rivian_climate.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rivian_climate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14rivian_climate.proto\x12\x06rivian\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n\x12\x43limateHoldSetting\x12\"\n\x1ahold_time_duration_seconds\x18\x01 \x01(\x05\"\xfe\x04\n\x11\x43limateHoldStatus\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .rivian.ClimateHoldStatus.Status\x12<\n\x0c\x61vailability\x18\x02 \x01(\x0e\x32&.rivian.ClimateHoldStatus.Availability\x12M\n\x15unavailability_reason\x18\x03 \x01(\x0e\x32..rivian.ClimateHoldStatus.UnavailabilityReason\x12\x31\n\rhold_end_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"i\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12STATUS_UNAVAILABLE\x10\x01\x12\x0e\n\nSTATUS_OFF\x10\x02\x12\r\n\tSTATUS_ON\x10\x03\x12\x10\n\x0cSTATUS_FAULT\x10\x04\"\x85\x01\n\x0c\x41vailability\x12\x1c\n\x18\x41VAILABILITY_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x41VAILABILITY_AVAILABLE\x10\x01\x12\x1d\n\x19\x41VAILABILITY_CONTROLLABLE\x10\x02\x12\x1c\n\x18\x41VAILABILITY_UNAVAILABLE\x10\x03\"\x83\x01\n\x14UnavailabilityReason\x12%\n!UNAVAILABILITY_REASON_UNSPECIFIED\x10\x00\x12!\n\x1dUNAVAILABILITY_REASON_UNKNOWN\x10\x01\x12!\n\x1dUNAVAILABILITY_REASON_LOW_SOC\x10\x02\"\x8e\x01\n\x17\x43\x61\x62inVentilationSetting\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x1c\n\x14windows_open_percent\x18\x03 \x01(\x05\x12\x1c\n\x14sunroof_open_percent\x18\x04 \x01(\x05\x12\x18\n\x10\x64uration_minutes\x18\x05 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rivian_climate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIMATEHOLDSETTING']._serialized_start=65
  _globals['_CLIMATEHOLDSETTING']._serialized_end=121
  _globals['_CLIMATEHOLDSTATUS']._serialized_start=124
  _globals['_CLIMATEHOLDSTATUS']._serialized_end=762
  _globals['_CLIMATEHOLDSTATUS_STATUS']._serialized_start=387
  _globals['_CLIMATEHOLDSTATUS_STATUS']._serialized_end=492
  _globals['_CLIMATEHOLDSTATUS_AVAILABILITY']._serialized_start=495
  _globals['_CLIMATEHOLDSTATUS_AVAILABILITY']._serialized_end=628
  _globals['_CLIMATEHOLDSTATUS_UNAVAILABILITYREASON']._serialized_start=631
  _globals['_CLIMATEHOLDSTATUS_UNAVAILABILITYREASON']._serialized_end=762
  _globals['_CABINVENTILATIONSETTING']._serialized_start=765
  _globals['_CABINVENTILATIONSETTING']._serialized_end=907
# @@protoc_insertion_point(module_scope)
