# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rivian_navigation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rivian_navigation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import rivian_base_pb2 as rivian__base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17rivian_navigation.proto\x12\x06rivian\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11rivian_base.proto\"\x8a\x01\n\x0cTripProgress\x12/\n\x0bleg_eta_utc\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0ctrip_eta_utc\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fnext_stop_index\x18\x03 \x01(\x05\"Q\n\x0cTripWaypoint\x12\"\n\x08location\x18\x01 \x01(\x0b\x32\x10.rivian.Location\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\"\x8f\x01\n\tTripRoute\x12\'\n\twaypoints\x18\x01 \x03(\x0b\x32\x14.rivian.TripWaypoint\x12\x17\n\x0f\x64istance_meters\x18\x02 \x01(\x05\x12\x18\n\x10\x64uration_seconds\x18\x03 \x01(\x05\x12\x13\n\x0binitial_soc\x18\x04 \x01(\x02\x12\x11\n\tfinal_soc\x18\x05 \x01(\x02\"\x84\x01\n\x0fTripPreferences\x12\x16\n\x0e\x61void_highways\x18\x01 \x01(\x08\x12\x13\n\x0b\x61void_tolls\x18\x02 \x01(\x08\x12\x15\n\ravoid_ferries\x18\x03 \x01(\x08\x12\x15\n\rfastest_route\x18\x04 \x01(\x08\x12\x16\n\x0emost_efficient\x18\x05 \x01(\x08\"u\n\x0f\x46\x61sterRouteInfo\x12\x1c\n\x14time_savings_seconds\x18\x01 \x01(\x05\x12\"\n\x1a\x64istance_difference_meters\x18\x02 \x01(\x05\x12 \n\x05route\x18\x03 \x01(\x0b\x32\x11.rivian.TripRoute\"\x8f\x02\n\x08TripInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12$\n\x06origin\x18\x02 \x01(\x0b\x32\x14.rivian.TripWaypoint\x12 \n\x05route\x18\x03 \x01(\x0b\x32\x11.rivian.TripRoute\x12,\n\x0bpreferences\x18\x04 \x01(\x0b\x32\x17.rivian.TripPreferences\x12\x1e\n\x16initial_soc_percentage\x18\x05 \x01(\x01\x12\x32\n\x0e\x64\x65parture_time\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\x0c\x66\x61ster_route\x18\x07 \x01(\x0b\x32\x17.rivian.FasterRouteInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rivian_navigation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRIPPROGRESS']._serialized_start=88
  _globals['_TRIPPROGRESS']._serialized_end=226
  _globals['_TRIPWAYPOINT']._serialized_start=228
  _globals['_TRIPWAYPOINT']._serialized_end=309
  _globals['_TRIPROUTE']._serialized_start=312
  _globals['_TRIPROUTE']._serialized_end=455
  _globals['_TRIPPREFERENCES']._serialized_start=458
  _globals['_TRIPPREFERENCES']._serialized_end=590
  _globals['_FASTERROUTEINFO']._serialized_start=592
  _globals['_FASTERROUTEINFO']._serialized_end=709
  _globals['_TRIPINFO']._serialized_start=712
  _globals['_TRIPINFO']._serialized_end=983
# @@protoc_insertion_point(module_scope)
