# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rivian_security.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rivian_security.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15rivian_security.proto\x12\x06rivian\"<\n\x08Geofence\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.rivian.GeofenceType\x12\x0c\n\x04name\x18\x02 \x01(\t\"8\n\x11\x46\x61voriteGeofences\x12#\n\tfavorites\x18\x01 \x03(\x0b\x32\x10.rivian.Geofence\"Z\n\"GearGuardStreamingInVehicleConsent\x12\x34\n\x0cuser_consent\x18\x01 \x01(\x0e\x32\x1e.rivian.GearGuardConsentStatus\"x\n\x1cGearGuardStreamingDailyLimit\x12\x36\n\x0b\x64\x61ily_limit\x18\x01 \x01(\x0e\x32!.rivian.GearGuardDailyLimitStatus\x12 \n\x18next_reset_time_unix_sec\x18\x02 \x01(\x03\"9\n\x13PassiveEntrySetting\x12\"\n\x1ahold_time_duration_seconds\x18\x01 \x01(\x05\"\x97\x01\n\x12PassiveEntryStatus\x12\x36\n.allow_passive_entry_via_bluetooth_while_in_ccc\x18\x01 \x01(\x08\x12I\n\x1d\x63\x63\x63_passive_permission_status\x18\x02 \x01(\x0e\x32\".rivian.CccPassivePermissionStatus*x\n\x0cGeofenceType\x12\x1e\n\x1aGEOFENCE_TYPE_UNRECOGNIZED\x10\x00\x12\x16\n\x12GEOFENCE_TYPE_HOME\x10\x01\x12\x16\n\x12GEOFENCE_TYPE_WORK\x10\x02\x12\x18\n\x14GEOFENCE_TYPE_CUSTOM\x10\x03*\xac\x01\n\x16GearGuardConsentStatus\x12#\n\x1fGEAR_GUARD_CONSENT_UNRECOGNIZED\x10\x00\x12\x18\n\x14GEAR_GUARD_CONSENTED\x10\x01\x12\x1c\n\x18GEAR_GUARD_NOT_CONSENTED\x10\x02\x12\x1d\n\x19GEAR_GUARD_NOT_APPLICABLE\x10\x03\x12\x16\n\x12GEAR_GUARD_UNKNOWN\x10\x04*\xae\x01\n\x19GearGuardDailyLimitStatus\x12\'\n#GEAR_GUARD_DAILY_LIMIT_UNRECOGNIZED\x10\x00\x12$\n GEAR_GUARD_DAILY_LIMIT_UNDEFINED\x10\x01\x12\"\n\x1eGEAR_GUARD_DAILY_LIMIT_NOT_HIT\x10\x02\x12\x1e\n\x1aGEAR_GUARD_DAILY_LIMIT_HIT\x10\x03*\xca\x01\n\x1a\x43\x63\x63PassivePermissionStatus\x12.\n*CCC_PASSIVE_PERMISSION_STATUS_UNRECOGNIZED\x10\x00\x12%\n!CCC_PASSIVE_PERMISSION_STATUS_SNA\x10\x01\x12)\n%CCC_PASSIVE_PERMISSION_STATUS_ENABLED\x10\x02\x12*\n&CCC_PASSIVE_PERMISSION_STATUS_DISABLED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rivian_security_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEOFENCETYPE']._serialized_start=580
  _globals['_GEOFENCETYPE']._serialized_end=700
  _globals['_GEARGUARDCONSENTSTATUS']._serialized_start=703
  _globals['_GEARGUARDCONSENTSTATUS']._serialized_end=875
  _globals['_GEARGUARDDAILYLIMITSTATUS']._serialized_start=878
  _globals['_GEARGUARDDAILYLIMITSTATUS']._serialized_end=1052
  _globals['_CCCPASSIVEPERMISSIONSTATUS']._serialized_start=1055
  _globals['_CCCPASSIVEPERMISSIONSTATUS']._serialized_end=1257
  _globals['_GEOFENCE']._serialized_start=33
  _globals['_GEOFENCE']._serialized_end=93
  _globals['_FAVORITEGEOFENCES']._serialized_start=95
  _globals['_FAVORITEGEOFENCES']._serialized_end=151
  _globals['_GEARGUARDSTREAMINGINVEHICLECONSENT']._serialized_start=153
  _globals['_GEARGUARDSTREAMINGINVEHICLECONSENT']._serialized_end=243
  _globals['_GEARGUARDSTREAMINGDAILYLIMIT']._serialized_start=245
  _globals['_GEARGUARDSTREAMINGDAILYLIMIT']._serialized_end=365
  _globals['_PASSIVEENTRYSETTING']._serialized_start=367
  _globals['_PASSIVEENTRYSETTING']._serialized_end=424
  _globals['_PASSIVEENTRYSTATUS']._serialized_start=427
  _globals['_PASSIVEENTRYSTATUS']._serialized_end=578
# @@protoc_insertion_point(module_scope)
